// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUvx28xlw08794OSbPbVdGvZtCqJLAEeQ',
    appId: '1:544912335575:web:6d4e1f38b527cd35a60692',
    messagingSenderId: '544912335575',
    projectId: 'fir-test-099-e273a',
    authDomain: 'fir-test-099-e273a.firebaseapp.com',
    storageBucket: 'fir-test-099-e273a.appspot.com',
    measurementId: 'G-4GNCV20B6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkIxQm3wuBruoVDkONd4nXr4K5QyuhGnA',
    appId: '1:544912335575:android:b7dd2645e7c6bcfba60692',
    messagingSenderId: '544912335575',
    projectId: 'fir-test-099-e273a',
    storageBucket: 'fir-test-099-e273a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzA5xsTVUGa7WRz0vACkyPhY0RGeq-mHs',
    appId: '1:544912335575:ios:7cc5f49de103cb49a60692',
    messagingSenderId: '544912335575',
    projectId: 'fir-test-099-e273a',
    storageBucket: 'fir-test-099-e273a.appspot.com',
    iosClientId: '544912335575-gapp5vug1vtf97vgrhkmc90q7pnknfi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest632021099',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzA5xsTVUGa7WRz0vACkyPhY0RGeq-mHs',
    appId: '1:544912335575:ios:7cc5f49de103cb49a60692',
    messagingSenderId: '544912335575',
    projectId: 'fir-test-099-e273a',
    storageBucket: 'fir-test-099-e273a.appspot.com',
    iosClientId: '544912335575-gapp5vug1vtf97vgrhkmc90q7pnknfi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest632021099',
  );
}
